29 correct choropleth mapbox layer implementation
Deltares/Guitares pull request #30
Opened 2023-07-11 12:17 UTC by panosatha

2023-07-11 12:25 UTC, panosatha commented
@maartenvanormondt can you check what happens with the legend of the choropleth? I followed your approach form the image layer but it doesn't seem to work. 

Another issue is a bug where while the legend is hidden, it reappears if you move the map.

2023-07-12 14:34 UTC, dladrichem requested changes

2023-07-12 14:34 UTC, dladrichem commented on src/guitares/pyqt5/mapbox/datashader_choropleth_layer.py
> +        print(f"{time.time() - t0} to make overlay")
Do you still need this?

2023-07-12 14:34 UTC, dladrichem commented on src/guitares/pyqt5/mapbox/datashader_choropleth_layer.py
> +        print(f"{time.time() - t0} to load the dataframe")
Also this and probably all t0's are for manual testing I assume? These can be removed now then

2023-07-12 14:34 UTC, dladrichem commented on src/guitares/pyqt5/mapbox/datashader_choropleth_layer.py
> +        print(f"{time.time() - t0} to convert the dataframe")
Same

2023-07-12 14:34 UTC, dladrichem commented on src/guitares/pyqt5/mapbox/geojson_layer_choropleth.py
> +        if not self.big_data:
Wouldn't it make more sense to put this in the update function as well?

2023-07-12 14:34 UTC, dladrichem commented on src/guitares/pyqt5/mapbox/geojson_layer_choropleth.py
> +        self.visible = True
Why do you first set self.visible, and then check for the same variable?

2023-07-12 14:34 UTC, dladrichem commented on src/guitares/pyqt5/mapbox/geojson_layer_heatmap.py
> +        print(f"{time.time() - t0} to parse heatmap geojson to mapbox")
Same

2023-07-14 15:29 UTC, panosatha commented on src/guitares/pyqt5/mapbox/datashader_choropleth_layer.py
> +        print(f"{time.time() - t0} to make overlay")
now deleted

2023-07-14 15:29 UTC, panosatha commented on src/guitares/pyqt5/mapbox/datashader_choropleth_layer.py
> +        print(f"{time.time() - t0} to load the dataframe")
correct

2023-07-14 15:32 UTC, panosatha commented on src/guitares/pyqt5/mapbox/geojson_layer_choropleth.py
> +        if not self.big_data:
the reason I did this is that if the data are not big_data I don't want to update them. Only when there are big data I want to load only at the zoom level.

2023-07-14 15:35 UTC, panosatha commented on src/guitares/pyqt5/mapbox/geojson_layer_choropleth.py
> +        self.visible = True
that variable can be changed based on the GUI callbacks. Here by default I want to see the data when I set them to the layer. 

The update method though i called everytime the user changes the zoom level or pans the map. Then if the layer is not visible I don't want anything to happen.

Maybe not the most efficient way. But I had to work with how Maarten has set-up the whole Guitares package.

2023-07-24 15:24 UTC, dladrichem approved these changes

2023-09-08 09:09 UTC, merged